### ISSUE TITLE
Crash after successful login. version 3.16 with ib-gateway 10.24.1f Linux

### ISSUE THREAD

**Issue by eyalco** [IbcAlpha/IBC#228]
**Bug**
version 3.16 with ib-gateway version 10.24.1f on Linux
After succesfull Login and 2FA. IBC shuts down with an error.

**To Reproduce**

1. Cloned the repo https://github.com/UnusualAlpha
/
[ib-gateway-docker](https://github.com/UnusualAlpha/ib-gateway-docker)
2. changed the version in \latest\Dockerfile to 10.24.1f in two places in the file , as needed.
3. The build is ok
4. I ran the docker (I had to get in with VNC and had to manually enter password and userid but this is for another issue)
5. gave 2FA
6. login successfully
7. CRASH
Expected behavior
After login I should be able to trade

**Container logs**
...
2023-09-05 17:15:54:407 IBC: Using default settings provider: ini file is /root/ibc/config.ini
2023-09-05 17:15:54:407 IBC: Using default login manager: getting username and password from args
2023-09-05 17:15:54:407 IBC: Using default main window manager
2023-09-05 17:15:54:407 IBC: Using default trading mode manager: constructor parameter args: tradingMode=live
2023-09-05 17:15:54:408 IBC: Using default config dialog manager
2023-09-05 17:15:54:411 IBC: CommandServer is not started because the port is not configured
2023-09-05 17:15:54:473 IBC: TWS Settings directory is: /root/Jts
2023-09-05 17:15:54:478 IBC: Ensuring /root/Jts/jts.ini contains required minimal lines
2023-09-05 17:15:54:478 IBC: Found setting: [Logon]/s3store=true
2023-09-05 17:15:54:478 IBC: Found setting: [Logon]/Locale=en
2023-09-05 17:15:54:478 IBC: Found setting: [Logon]/displayedproxymsg=1
2023-09-05 17:15:54:478 IBC: Found setting: [Logon]/UseSSL=true
2023-09-05 17:15:54:478 IBC: Found setting: [IBGateway]/ApiOnly=true
2023-09-05 17:15:54:478 IBC: Confirmed /root/Jts/jts.ini contains required minimal lines
2023-09-05 17:15:54:478 IBC: Starting Gateway
2023-09-05 17:15:54:478 IBC: Starting session: will exit if login dialog is not displayed within 60 seconds
2023-09-05 17:15:55:826 IBC: Getting config dialog
2023-09-05 17:15:55:826 IBC: Creating config dialog future
2023-09-05 17:15:55:827 IBC: Getting main window
2023-09-05 17:15:55:827 IBC: Creating main window future
2023-09-05 17:15:56:879 IBC: Detected frame entitled: IBKR Gateway; event=Activated
2023-09-05 17:15:56:884 IBC: Detected frame entitled: IBKR Gateway; event=Focused
2023-09-05 17:15:56:884 IBC: Detected frame entitled: IBKR Gateway; event=Opened
2023/09/05 17:16:06 socat[498] E connect(5, AF=2 127.0.0.1:4000, 16): Connection refused
2023-09-05 17:16:09:095 IBC: Detected frame entitled: IBKR Gateway; event=Lost focus
2023-09-05 17:16:09:096 IBC: Detected frame entitled: IBKR Gateway; event=Deactivated
2023-09-05 17:16:09:099 IBC: Detected frame entitled: Loading...; event=Activated
2023-09-05 17:16:09:104 IBC: Detected frame entitled: Loading...; event=Focused
2023-09-05 17:16:09:104 IBC: Detected frame entitled: Loading...; event=Opened
2023-09-05 17:16:09:104 IBC: Found Gateway main window
2023-09-05 17:16:09:104 IBC: Got main window from future
2023-09-05 17:16:09:104 IBC: Invoking config dialog menu
2023-09-05 17:16:09:138 IBC: Detected frame entitled: Loading...; event=Lost focus
2023-09-05 17:16:09:138 IBC: Detected frame entitled: Loading...; event=Deactivated
2023-09-05 17:16:09:138 IBC: Detected frame entitled: Authenticating (trying for another 19 seconds)...; event=Activated
2023-09-05 17:16:09:138 IBC: Detected frame entitled: Authenticating (trying for another 19 seconds)...; event=Focused
2023-09-05 17:16:09:139 IBC: Detected frame entitled: Authenticating (trying for another 19 seconds)...; event=Opened
2023-09-05 17:16:09:235 IBC: Detected dialog entitled: Second Factor Authentication; event=Opened
2023-09-05 17:16:09:236 IBC: Second Factor Authentication initiated
2023-09-05 17:16:09:241 IBC: Detected frame entitled: Authenticating (trying for another 19 seconds)...; event=Lost focus
2023-09-05 17:16:09:242 IBC: Detected frame entitled: Authenticating (trying for another 19 seconds)...; event=Deactivated
2023-09-05 17:16:09:242 IBC: Detected dialog entitled: Second Factor Authentication; event=Activated
2023-09-05 17:16:09:242 IBC: Detected dialog entitled: Second Factor Authentication; event=Focused
2023/09/05 17:16:14 socat[529] E connect(5, AF=2 127.0.0.1:4000, 16): Connection refused
2023/09/05 17:16:18 socat[537] E connect(5, AF=2 127.0.0.1:4000, 16): Connection refused
2023-09-05 17:16:19:257 IBC: Detected dialog entitled: Second Factor Authentication; event=Lost focus
2023-09-05 17:16:19:257 IBC: Detected dialog entitled: Second Factor Authentication; event=Deactivated
2023-09-05 17:16:19:257 IBC: Detected dialog entitled: Second Factor Authentication; event=Closed
2023-09-05 17:16:19:258 IBC: Duration since login: 10 seconds
2023-09-05 17:16:19:258 IBC: If login has not completed, IBC will exit in 40 seconds
2023-09-05 17:16:19:331 IBC: Detected dialog entitled: Second Factor Authentication; event=Opened
2023-09-05 17:16:19:336 IBC: Detected dialog entitled: Second Factor Authentication; event=Activated
2023-09-05 17:16:19:337 IBC: Detected dialog entitled: Second Factor Authentication; event=Focused
2023-09-05 17:16:23:004 IBC: Detected dialog entitled: Second Factor Authentication; event=Lost focus
2023-09-05 17:16:23:004 IBC: Detected dialog entitled: Second Factor Authentication; event=Deactivated
2023-09-05 17:16:23:005 IBC: Detected dialog entitled: Second Factor Authentication; event=Closed
2023/09/05 17:16:23 socat[550] E connect(5, AF=2 127.0.0.1:4000, 16): Connection refused
2023-09-05 17:16:24:574 IBC: Detected dialog entitled: Downloading settings from server; event=Closed
LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j Verd.x
2023-09-05 17:16:26:957 IBC: Detected dialog entitled: U11XXXXXX TWS Configuration; event=Opened
2023-09-05 17:16:26:957 IBC: Detected dialog entitled: U11XXXXXX TWS Configuration; event=Activated
2023-09-05 17:16:26:957 IBC: Got config dialog from future
2023-09-05 17:16:26:958 IBC: Detected dialog entitled: U11XXXXXX TWS Configuration; event=Focused
2023-09-05 17:16:26:958 IBC: Detected frame entitled: Starting application...; event=Closed
2023-09-05 17:16:26:958 IBC: Login has completed
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-09-05 17:16:26:958 IBC: An exception has occurred:
java.lang.NullPointerException
at ibcalpha.ibc.LoginManager.setLoginState(Unknown Source)
at ibcalpha.ibc.SplashFrameHandler.handleWindow(Unknown Source)
at ibcalpha.ibc.TwsListener.lambda$eventDispatched$0(Unknown Source)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-09-05 17:16:26:959 IBC: Exiting with exit code=1100
IBC returned exit status 76
Renaming TWS or Gateway .exe file to original name
Gateway finished

OS: linux

**Comment by rlktradewright** [comment]
IBC 3.16 does not support Gateway 10.22 or later. You need at least 3.17.0, - see the release description at https://github.com/IbcAlpha/IBC/releases/tag/3.17.0.

My advice would be to use the latest version, 3.18.0, and see if that still gives you a problem.

**Comment by eyalco** [comment]
Thanks,
3.18 works.
