### ISSUE TITLE
IBC crashed with Exiting with exit code=1100

### ISSUE THREAD

**Issue by Amir-Inbar** [IbcAlpha/IBC#278]
Hi everyone,

I've been running the IBC container overnight, but when I checked in the morning, I noticed the pod had gone haywire. This isn't the first time it's happened, so I grabbed the logs. Could this be an issue with IBC?

Any insights would be appreciated!

2024-12-09 08:13:20 2024-12-09 01:13:20:403 IBC: using default settings provider: ini file is /home/ibgateway/ibc/config.ini
2024-12-09 08:13:20 2024-12-09 01:13:20:403 IBC: using default login manager: will get username and password from settings; FIX username and password (if required) from settings
2024-12-09 08:13:20 2024-12-09 01:13:20:404 IBC: using default main window manager
2024-12-09 08:13:20 2024-12-09 01:13:20:404 IBC: using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
2024-12-09 08:13:20 2024-12-09 01:13:20:407 IBC: using default config dialog manager
2024-12-09 08:13:20 2024-12-09 01:13:20:411 IBC: CommandServer is not started because the port is not configured
2024-12-09 08:13:20 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-12-09 08:13:20 2024-12-09 01:13:20:430 IBC: An exception has occurred:
2024-12-09 08:13:20 java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
2024-12-09 08:13:20     at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
2024-12-09 08:13:20     at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
2024-12-09 08:13:20     at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
2024-12-09 08:13:20     at java.security.AccessController.doPrivileged(Native Method)
2024-12-09 08:13:20     at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
2024-12-09 08:13:20     at java.lang.Class.forName0(Native Method)
2024-12-09 08:13:20     at java.lang.Class.forName(Class.java:264)
2024-12-09 08:13:20     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
2024-12-09 08:13:20     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
2024-12-09 08:13:20     at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
2024-12-09 08:13:20     at java.lang.Class.forName0(Native Method)
2024-12-09 08:13:20     at java.lang.Class.forName(Class.java:264)
2024-12-09 08:13:20     at java.awt.Toolkit$2.run(Toolkit.java:860)
2024-12-09 08:13:20     at java.awt.Toolkit$2.run(Toolkit.java:855)
2024-12-09 08:13:20     at java.security.AccessController.doPrivileged(Native Method)
2024-12-09 08:13:20     at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
2024-12-09 08:13:20     at ibcalpha.ibc.IbcTws.createToolkitListener(Unknown Source)
2024-12-09 08:13:20     at ibcalpha.ibc.IbcTws.load(Unknown Source)
2024-12-09 08:13:20     at ibcalpha.ibc.IbcGateway.main(Unknown Source)
2024-12-09 08:13:20 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-12-09 08:13:20 2024-12-09 01:13:20:432 IBC: Exiting with exit code=1100
2024-12-09 08:13:20 IBC returned exit status 76
2024-12-09 08:13:20 autorestart file found at /home/ibgateway/Jts/kjiomliadnkbejgehhdmgdkahmigahnhminejpce/autorestart
2024-12-09 08:13:20 AUTORESTART_OPTION is -Drestart=kjiomliadnkbejgehhdmgdkahmigahnhminejpce
2024-12-09 08:13:20 IBC will restart shortly
2024-12-09 08:13:20 sleep 2
2024-12-09 08:13:20 Starting Gateway with this command:
2024-12-09 08:13:20 "/usr/local/i4j_jres/Oda-jK0QgTEmVssfllLP/1.8.0_202/bin/java" -cp "/home/ibgateway/Jts/ibgateway/10.32.1m/jars/batik-all-1.16.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/commons-io-2.11.0.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/fop-2.8.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jackson-annotations-2.12.3.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jackson-core-2.12.3.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jackson-databind-2.12.3.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jts4launch-1032.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jxbrowser-7.29.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jxbrowser-linux64-7.29.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/jxbrowser-swing-7.29.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/locales.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/log4j-api-2.17.1.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/log4j-core-2.17.1.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/total-2023.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/twslaunch-1032.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/twslaunch-install4j-1.12.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/jars/xmlgraphics-commons-2.8.jar:/home/ibgateway/Jts/ibgateway/10.32.1m/.install4j/i4jruntime.jar:/home/ibgateway/ibc/IBC.jar" -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dtwslaunch.autoupdate.serviceImpl=com.ib.tws.twslaunch.install4j.Install4jAutoUpdateService -Dchannel=latest -Dexe4j.isInstall4j=true -Dinstall4jType=standalone -DjtsConfigDir=/home/ibgateway/Jts -Dibcsessionid=F0fS3TW0 -Drestart=kjiomliadnkbejgehhdmgdkahmigahnhminejpce ibcalpha.ibc.IbcGateway "/home/ibgateway/ibc/config.ini"

**Comment by rlktradewright** [comment]
No it's not an IBC issue, it's an X11 issue. You probably need to use xvfb. Try groogling 'Can't connect to X11 window server using ':1' as the value of the DISPLAY variable'. Or contact whoever produced the container image.
