### ISSUE TITLE
Cannot start TWS 978.1o

### ISSUE THREAD

**Issue by lihanchen** [IbcAlpha/IBC#84]
I tried to use IBC to start TWS 978.1o offline.
It can fill in login credentials and login. After tws splash screen, the main window doesn't show up.
The IBC window is still green.

I can use IBC to start IB Gateway without problems. I can start TWS manually.

Log:

```
================================================================================

Starting IBC version 3.8.2 on 2020-04-03 at 15:46:56

Operating system: Linux LHC-DEV-Desktop 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Arguments:

TWS version = 978
Entry point = ibcalpha.ibc.IbcTws
--tws-path = /home/lhc/Jts
--tws-settings-path = 
--ibc-path = /home/lhc/projects/IBC/resources
--ibc-ini = /home/lhc/projects/IBC/resources/config.ini
--mode = 
--java-path = 
--user =
--pw =

=================================
Generating the classpath
Classpath=/home/lhc/Jts/978/jars/jts4launch-978.jar:/home/lhc/Jts/978/jars/locales.jar:/home/lhc/Jts/978/jars/log4j-api-2.5.jar:/home/lhc/Jts/978/jars/log4j-core-2.5.jar:/home/lhc/Jts/978/jars/total-2018.jar:/home/lhc/Jts/978/jars/twslaunch-978.jar:/home/lhc/Jts/978/jars/twslaunch-install4j-1.9.jar:/home/lhc/projects/IBC/resources/IBC.jar

Generating the JAVA VM options
Java VM Options=-Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70

Determining the location of java executable
Location of java executable=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin

Starting TWS with this command:
"/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" -cp "/home/lhc/Jts/978/jars/jts4launch-978.jar:/home/lhc/Jts/978/jars/locales.jar:/home/lhc/Jts/978/jars/log4j-api-2.5.jar:/home/lhc/Jts/978/jars/log4j-core-2.5.jar:/home/lhc/Jts/978/jars/total-2018.jar:/home/lhc/Jts/978/jars/twslaunch-978.jar:/home/lhc/Jts/978/jars/twslaunch-install4j-1.9.jar:/home/lhc/projects/IBC/resources/IBC.jar" -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 ibcalpha.ibc.IbcTws "/home/lhc/projects/IBC/resources/config.ini"  

2020-04-03 15:46:57:091 IBC: Version: 3.8.2
System Properties
------------------------------------------------------------
java.runtime.name = OpenJDK Runtime Environment
sun.boot.library.path = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
java.vm.version = 25.242-b08
java.vm.vendor = Private Build
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = OpenJDK 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /home/lhc/Jts
java.runtime.version = 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/local/lib/:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64::/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 5.3.0-42-generic
user.home = /home/lhc
user.timezone = America/Los_Angeles
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.8
java.class.path = /home/lhc/Jts/978/jars/jts4launch-978.jar:/home/lhc/Jts/978/jars/locales.jar:/home/lhc/Jts/978/jars/log4j-api-2.5.jar:/home/lhc/Jts/978/jars/log4j-core-2.5.jar:/home/lhc/Jts/978/jars/total-2018.jar:/home/lhc/Jts/978/jars/twslaunch-978.jar:/home/lhc/Jts/978/jars/twslaunch-install4j-1.9.jar:/home/lhc/projects/IBC/resources/IBC.jar
user.name = lhc
java.vm.specification.version = 1.8
sun.java.command = ibcalpha.ibc.IbcTws /home/lhc/projects/IBC/resources/config.ini
java.home = /usr/lib/jvm/java-8-openjdk-amd64/jre
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.8.0_242
java.ext.dirs = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
java.vendor = Private Build
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = gnome
sun.cpu.isalist = 
------------------------------------------------------------
2020-04-03 15:46:57:092 IBC: Using default settings provider: ini file is /home/lhc/projects/IBC/resources/config.ini
2020-04-03 15:46:57:092 IBC: Using default login manager: getting username and password from args but not found. Will get from settings
2020-04-03 15:46:57:092 IBC: Using default main window manager: constructor parameter isGateway=false
2020-04-03 15:46:57:092 IBC: Using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
2020-04-03 15:46:57:093 IBC: Using default config dialog manager
2020-04-03 15:46:57:098 IBC: CommandServer is not started because the port is not configured
2020-04-03 15:46:57:180 IBC: TWS Settings directory is: /home/lhc/Jts
2020-04-03 15:46:57:184 IBC: Ensuring /home/lhc/Jts/jts.ini contains required minimal lines
2020-04-03 15:46:57:184 IBC: Found setting: [Logon]/s3store=true
2020-04-03 15:46:57:184 IBC: Found setting: [Logon]/Locale=en
2020-04-03 15:46:57:184 IBC: Found setting: [Logon]/displayedproxymsg=1
2020-04-03 15:46:57:184 IBC: Found setting: [IBGateway]/ApiOnly=true
2020-04-03 15:46:57:184 IBC: Confirmed /home/lhc/Jts/jts.ini contains required minimal lines
2020-04-03 15:46:59:998 IBC: Detected frame entitled: Login; event=Opened
2020-04-03 15:47:00:000 IBC: Trading mode from settings: tradingMode=paper
2020-04-03 15:47:00:000 IBC: Setting Trading mode = paper
2020-04-03 15:47:00:090 IBC: Setting user name
2020-04-03 15:47:00:092 IBC: Setting password
2020-04-03 15:47:00:246 IBC: Detected frame entitled: Login; event=Activated
2020-04-03 15:47:00:292 IBC: Click button: Paper Log In
2020-04-03 15:47:00:454 IBC: Button now disabled: Paper Log In
2020-04-03 15:47:01:059 IBC: Detected frame entitled: Authenticating...; event=Opened
2020-04-03 15:47:01:081 IBC: Detected frame entitled: Authenticating...; event=Activated
LogModuleConfigurator-Init: Log4j Ver2.x found on classpath
LogModuleConfigurator-Init: LogModuleConfigurator initialized with Log4j Verd.x
org.w3c.dom.DOMException: jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:776)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:868)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:563)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at feature.svg.b.a(b.java:90)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at feature.svg.b.a(b.java:79)
	at feature.svg.b.a(b.java:64)
	at feature.svg.d.a(d.java:85)
	at twslaunch.trader.common.k.b(k.java:772)
	at twslaunch.trader.common.k.a(k.java:749)
	at twslaunch.trader.common.k.c(k.java:745)
	at twslaunch.trader.common.c.a(c.java:305)
	at twslaunch.trader.common.c.c(c.java:283)
	at feature.gfis.component.b.b(b.java:68)
	at feature.gfis.component.b.<init>(b.java:61)
	at feature.tabs.bf.f(bf.java:183)
	at feature.tabs.bf.<init>(bf.java:156)
	at feature.tabs.bg.<init>(bg.java:437)
	at jclient.qk.b(qk.java:847)
	at jclient.qk.eG(qk.java:831)
	at jclient.qk.co(qk.java:978)
	at trader.tab.bc.cn(bc.java:1532)
	at trader.tab.bc.<init>(bc.java:1522)
	at jclient.qi.<init>(qi.java:216)
	at jclient.qj.<init>(qj.java:492)
	at jclient.qk.<init>(qk.java:513)
	at jclient.qk.<init>(qk.java:509)
	at feature.mainwin.B.a(B.java:257)
	at feature.mainwin.B.a(B.java:139)
	at feature.mainwin.v.a(v.java:175)
	at trader.common.factory.U.a(U.java:249)
	at trader.common.factory.U.a(U.java:216)
	at feature.mainwin.B.a(B.java:173)
	at trader.tab.g.a(g.java:1227)
	at trader.common.factory.b.a(b.java:1509)
	at trader.common.factory.b.c(b.java:1524)
	at trader.common.factory.b.b(b.java:1583)
	at trader.common.factory.b.b(b.java:1467)
	at jclient.f8.b(f8.java:3687)
	at twslaunch.jutils.as.a(as.java:713)
	at jclient.f8.a(f8.java:3685)
	at jclient.f8.a(f8.java:2888)
	at feature.welcome.a.b(a.java:361)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR: null
Enclosed Exception:
jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
org.w3c.dom.DOMException: jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:776)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:868)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:563)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at feature.svg.b.a(b.java:90)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at feature.svg.b.a(b.java:79)
	at feature.svg.b.a(b.java:60)
	at feature.svg.c.a(c.java:58)
	at twslaunch.trader.common.c.a(c.java:454)
	at twslaunch.trader.common.c.a(c.java:450)
	at twslaunch.trader.common.c.a(c.java:310)
	at twslaunch.trader.common.c.c(c.java:283)
	at feature.gfis.component.b.b(b.java:68)
	at feature.gfis.component.b.<init>(b.java:61)
	at feature.tabs.bf.f(bf.java:183)
	at feature.tabs.bf.<init>(bf.java:156)
	at feature.tabs.bg.<init>(bg.java:437)
	at jclient.qk.b(qk.java:847)
	at jclient.qk.eG(qk.java:831)
	at jclient.qk.co(qk.java:978)
	at trader.tab.bc.cn(bc.java:1532)
	at trader.tab.bc.<init>(bc.java:1522)
	at jclient.qi.<init>(qi.java:216)
	at jclient.qj.<init>(qj.java:492)
	at jclient.qk.<init>(qk.java:513)
	at jclient.qk.<init>(qk.java:509)
	at feature.mainwin.B.a(B.java:257)
	at feature.mainwin.B.a(B.java:139)
	at feature.mainwin.v.a(v.java:175)
	at trader.common.factory.U.a(U.java:249)
	at trader.common.factory.U.a(U.java:216)
	at feature.mainwin.B.a(B.java:173)
	at trader.tab.g.a(g.java:1227)
	at trader.common.factory.b.a(b.java:1509)
	at trader.common.factory.b.c(b.java:1524)
	at trader.common.factory.b.b(b.java:1583)
	at trader.common.factory.b.b(b.java:1467)
	at jclient.f8.b(f8.java:3687)
	at twslaunch.jutils.as.a(as.java:713)
	at jclient.f8.a(f8.java:3685)
	at jclient.f8.a(f8.java:2888)
	at feature.welcome.a.b(a.java:361)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR: null
Enclosed Exception:
jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
org.w3c.dom.DOMException: jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:776)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:868)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
	at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:563)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at feature.svg.b.a(b.java:90)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at feature.svg.b.a(b.java:79)
	at feature.svg.b.a(b.java:60)
	at feature.svg.c.a(c.java:66)
	at jtscomponents.plaf.dT.a(dT.java:2402)
	at feature.gfis.component.b.onFontChanged(b.java:109)
	at feature.gfis.component.b.b(b.java:76)
	at feature.gfis.component.b.<init>(b.java:61)
	at feature.tabs.bf.f(bf.java:183)
	at feature.tabs.bf.<init>(bf.java:156)
	at feature.tabs.bg.<init>(bg.java:437)
	at jclient.qk.b(qk.java:847)
	at jclient.qk.eG(qk.java:831)
	at jclient.qk.co(qk.java:978)
	at trader.tab.bc.cn(bc.java:1532)
	at trader.tab.bc.<init>(bc.java:1522)
	at jclient.qi.<init>(qi.java:216)
	at jclient.qj.<init>(qj.java:492)
	at jclient.qk.<init>(qk.java:513)
	at jclient.qk.<init>(qk.java:509)
	at feature.mainwin.B.a(B.java:257)
	at feature.mainwin.B.a(B.java:139)
	at feature.mainwin.v.a(v.java:175)
	at trader.common.factory.U.a(U.java:249)
	at trader.common.factory.U.a(U.java:216)
	at feature.mainwin.B.a(B.java:173)
	at trader.tab.g.a(g.java:1227)
	at trader.common.factory.b.a(b.java:1509)
	at trader.common.factory.b.c(b.java:1524)
	at trader.common.factory.b.b(b.java:1583)
	at trader.common.factory.b.b(b.java:1467)
	at jclient.f8.b(f8.java:3687)
	at twslaunch.jutils.as.a(as.java:713)
	at jclient.f8.a(f8.java:3685)
	at jclient.f8.a(f8.java:2888)
	at feature.welcome.a.b(a.java:361)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR: null
Enclosed Exception:
jar:file:/home/lhc/Jts/978/jars/jts4launch-978.jar!/trader/common/images/gfis_blue_w47_h16.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
Original message:
String index out of range: 4
2020-04-03 15:47:21:724 IBC: Detected frame entitled: Starting application...; event=Closed
```

**Comment by rlktradewright** [comment]
[Please, please, please in future don't quote the logfile inline: it's just a pain in the butt to work with. Attach it! Then I can open it in the editor of my choice, easily get to the end of the long lines, used advanced searches, etc. ]

It's late at night here and I haven't tried installing this TWS version on Ubuntu yet, but it works fine on Windows (I get exactly the same exceptions reported, but it still manages to find the main window).

I notice that somehow you are using OpenJDK instead of the 'private' Oracle JDK that gets installed with TWS, somewhere like ~/.i4j_jres/1.8.0_152-tzdata2019c_64. Have you perhaps deleted that folder, because the script should find that first if it's there.

In the past TWS has had problems with OpenJDK, so maybe that's what's causing your problem.

**Comment by lihanchen** [comment]
Using the IB jre fixed the problem. Thanks.
For some reason IBC picked up the OpenJDK I installed on my machine. I put it in JAVA_HOME and PATH. I need to explicitly set JAVA_PATH in twsstart.sh to make it work.
